/**
 * AI Launch QA — Deterministic & AI Check Definitions
 * 28+ check definitions across 6 QA categories with severity rules, impact statements, and recommendations
 */

import { QACategory, Severity } from '../../types/audit';

export interface CheckDefinition {
  id: string;
  category: QACategory;
  name: string;
  description: string;
  defaultSeverity: Severity;
  weight: number; // weight in category score penalty
  impactTemplate: string;
  recommendationTemplate: string;
}

export const CHECK_DEFINITIONS: Record<string, CheckDefinition> = {
  // --- Availability & Functionality (Weight 25%) ---
  'availability.http-status': {
    id: 'availability.http-status',
    category: 'functionality',
    name: 'HTTP 200 Availability & Status',
    description: 'Ensures target URLs return successful HTTP 200 OK status without fatal server crashes.',
    defaultSeverity: 'critical',
    weight: 25,
    impactTemplate: 'Users and search engines cannot access the website if it returns a 5xx or 4xx status.',
    recommendationTemplate: 'Verify deployment server configuration and router endpoints.',
  },
  'availability.console-errors': {
    id: 'availability.console-errors',
    category: 'functionality',
    name: 'Uncaught JavaScript Runtime Errors',
    description: 'Monitors the browser runtime console for unhandled exceptions, type errors, or script failures.',
    defaultSeverity: 'high',
    weight: 20,
    impactTemplate: 'Unhandled runtime exceptions can halt React renders and break client-side interactivity.',
    recommendationTemplate: 'Add error boundaries and resolve undefined variable accesses.',
  },
  'functionality.broken-links': {
    id: 'functionality.broken-links',
    category: 'functionality',
    name: 'Broken Internal & External Hyperlinks',
    description: 'Validates discovered href targets to ensure they do not lead to 404 or dead endpoints.',
    defaultSeverity: 'high',
    weight: 15,
    impactTemplate: 'Broken links erode user trust and disrupt conversion funnels.',
    recommendationTemplate: 'Update or remove broken hyperlink URLs or configure proper redirect fallback.',
  },
  'functionality.dead-buttons': {
    id: 'functionality.dead-buttons',
    category: 'functionality',
    name: 'Dead Interactive Elements / Empty Callbacks',
    description: 'Detects button elements lacking event listeners, type attributes, or accessible trigger actions.',
    defaultSeverity: 'high',
    weight: 18,
    impactTemplate: 'Users clicking on key action buttons will experience no response or visual feedback.',
    recommendationTemplate: 'Wire onClick handlers or form submit actions to interactive button components.',
  },
  'functionality.empty-hrefs': {
    id: 'functionality.empty-hrefs',
    category: 'functionality',
    name: 'Empty or Placeholder href Attributes (href="#" / href="")',
    description: 'Identifies anchor links pointing to empty hash anchors without route handlers.',
    defaultSeverity: 'medium',
    weight: 10,
    impactTemplate: 'Clicking empty anchors scrolls to top without navigating to intended destination.',
    recommendationTemplate: 'Replace placeholder href="#" with actual route paths or semantic <button> tags.',
  },
  'functionality.unlabeled-interactive': {
    id: 'functionality.unlabeled-interactive',
    category: 'functionality',
    name: 'Unlabeled Interactive Controls',
    description: 'Detects icon-only buttons or toggles lacking visible text or aria-labels.',
    defaultSeverity: 'medium',
    weight: 10,
    impactTemplate: 'Screen readers and assistive technologies cannot announce the control purpose.',
    recommendationTemplate: 'Add aria-label or title attributes to icon buttons.',
  },

  // --- Mobile & Responsive (Weight 20%) ---
  'mobile.horizontal-overflow': {
    id: 'mobile.horizontal-overflow',
    category: 'mobile',
    name: 'Mobile Horizontal Viewport Overflow',
    description: 'Tests if content expands beyond device width (375px/390px) forcing horizontal scroll.',
    defaultSeverity: 'critical',
    weight: 25,
    impactTemplate: 'Horizontal page shaking and broken viewport bounds severely harm mobile UX.',
    recommendationTemplate: 'Apply `overflow-x-hidden` or set max-w-full / responsive flex-wrap on wide containers.',
  },
  'mobile.viewport-clipping': {
    id: 'mobile.viewport-clipping',
    category: 'mobile',
    name: 'Viewport Element Clipping & Cropped CTAs',
    description: 'Checks if primary buttons, modals, or banners are clipped off-screen on compact displays.',
    defaultSeverity: 'high',
    weight: 20,
    impactTemplate: 'Users cannot tap conversion buttons clipped outside the screen.',
    recommendationTemplate: 'Use dynamic height `min-h-dvh` and responsive padding `px-4 py-2` on mobile.',
  },
  'mobile.touch-targets': {
    id: 'mobile.touch-targets',
    category: 'mobile',
    name: 'Touch Target Sizing (Min 44x44px)',
    description: 'Verifies interactive buttons and links meet the minimum 44px recommended touch target height/width.',
    defaultSeverity: 'medium',
    weight: 12,
    impactTemplate: 'Small touch targets cause accidental taps on adjacent items on mobile touchscreens.',
    recommendationTemplate: 'Ensure touchable buttons have at least 44x44px bounding area with adequate padding.',
  },
  'mobile.text-size': {
    id: 'mobile.text-size',
    category: 'mobile',
    name: 'Legible Mobile Typography (Min 12px)',
    description: 'Checks for sub-12px font sizes that force zooming on small screens.',
    defaultSeverity: 'low',
    weight: 8,
    impactTemplate: 'Tiny text strains mobile readability and triggers automatic zoom on iOS Safari.',
    recommendationTemplate: 'Increase body font size to at least 14px (text-sm or text-base).',
  },
  'mobile.element-overlap': {
    id: 'mobile.element-overlap',
    category: 'mobile',
    name: 'Responsive Element Collision & Overlap',
    description: 'Detects overlapping z-index elements obscuring text or controls when screen narrows.',
    defaultSeverity: 'high',
    weight: 18,
    impactTemplate: 'Sticky headers or absolute positioned badges cover underlying text or buttons.',
    recommendationTemplate: 'Ensure proper stacking contexts, margins, and flex-col layouts on mobile breakpoints.',
  },

  // --- Accessibility (Weight 15%) ---
  'accessibility.color-contrast': {
    id: 'accessibility.color-contrast',
    category: 'accessibility',
    name: 'WCAG AA Color Contrast Ratios',
    description: 'Validates text-to-background contrast ratio meets WCAG 2.1 AA (4.5:1 for normal text, 3:1 for large text).',
    defaultSeverity: 'high',
    weight: 20,
    impactTemplate: 'Low contrast makes text illegible for users with visual impairments or in direct sunlight.',
    recommendationTemplate: 'Adjust foreground or background color to satisfy WCAG AA 4.5:1 contrast standards.',
  },
  'accessibility.image-alt': {
    id: 'accessibility.image-alt',
    category: 'accessibility',
    name: 'Image Descriptive alt Attributes',
    description: 'Scans all <img> elements for missing or empty alt attributes.',
    defaultSeverity: 'medium',
    weight: 15,
    impactTemplate: 'Screen reader users cannot understand the context or meaning of visual images.',
    recommendationTemplate: 'Add descriptive alt text or alt="" if the image is purely decorative.',
  },
  'accessibility.form-labels': {
    id: 'accessibility.form-labels',
    category: 'accessibility',
    name: 'Explicit Form Input Labels (<label> / aria-label)',
    description: 'Ensures every <input>, <select>, and <textarea> has an associated label or aria-label.',
    defaultSeverity: 'high',
    weight: 18,
    impactTemplate: 'Form fields without labels leave assistive technology users unable to fill out forms.',
    recommendationTemplate: 'Add <label htmlFor="..."> tags or aria-label attributes to input elements.',
  },
  'accessibility.heading-hierarchy': {
    id: 'accessibility.heading-hierarchy',
    category: 'accessibility',
    name: 'Logical Heading Structure (H1-H6)',
    description: 'Validates single top-level <h1> and prevents skipped heading levels (e.g. h1 directly to h4).',
    defaultSeverity: 'medium',
    weight: 12,
    impactTemplate: 'Disordered heading levels prevent screen reader navigation by page structure.',
    recommendationTemplate: 'Structure headings hierarchically from h1 through h2, h3 without skipping levels.',
  },
  'accessibility.landmark-regions': {
    id: 'accessibility.landmark-regions',
    category: 'accessibility',
    name: 'Semantic Landmark Regions (<main>, <header>, <nav>)',
    description: 'Checks for semantic HTML5 landmarks for primary content areas.',
    defaultSeverity: 'low',
    weight: 10,
    impactTemplate: 'Lack of landmarks slows down screen reader users navigating large documents.',
    recommendationTemplate: 'Wrap major layout sections in <header>, <main>, <nav>, and <footer> landmarks.',
  },

  // --- Performance & Core Web Vitals (Weight 15%) ---
  'performance.lcp': {
    id: 'performance.lcp',
    category: 'performance',
    name: 'Largest Contentful Paint (LCP < 2.5s)',
    description: 'Measures when the main content element is likely rendered and visible.',
    defaultSeverity: 'high',
    weight: 25,
    impactTemplate: 'Slow LCP (>2.5s) causes user drop-off and negatively impacts SEO ranking.',
    recommendationTemplate: 'Optimize hero images with modern WebP/AVIF formats, preload fonts, and reduce server response time.',
  },
  'performance.cls': {
    id: 'performance.cls',
    category: 'performance',
    name: 'Cumulative Layout Shift (CLS < 0.1)',
    description: 'Measures unexpected visual layout shifts during page loading.',
    defaultSeverity: 'medium',
    weight: 18,
    impactTemplate: 'Layout shifts cause users to accidentally click wrong links while elements jump around.',
    recommendationTemplate: 'Specify explicit width and height dimensions on images and reserve space for dynamic ads/embeds.',
  },
  'performance.render-blocking': {
    id: 'performance.render-blocking',
    category: 'performance',
    name: 'Render-Blocking Scripts & Stylesheets',
    description: 'Identifies critical path resources in <head> delaying initial page paint.',
    defaultSeverity: 'medium',
    weight: 15,
    impactTemplate: 'Synchronous scripts block HTML parsing until download finishes.',
    recommendationTemplate: 'Add `defer` or `async` attributes to script tags and inline critical CSS.',
  },
  'performance.resource-weight': {
    id: 'performance.resource-weight',
    category: 'performance',
    name: 'Total JavaScript & Asset Weight',
    description: 'Analyzes bundle size and compressed payload weights.',
    defaultSeverity: 'low',
    weight: 12,
    impactTemplate: 'Bloated bundle sizes increase data usage and startup latency on 4G/mobile networks.',
    recommendationTemplate: 'Implement code splitting via dynamic imports and compress static assets.',
  },

  // --- SEO & Social Metadata (Weight 10%) ---
  'seo.title': {
    id: 'seo.title',
    category: 'seo',
    name: 'Page <title> Tag Presence & Length',
    description: 'Checks for a descriptive title tag between 30 and 65 characters.',
    defaultSeverity: 'high',
    weight: 20,
    impactTemplate: 'Missing or generic titles hurt organic search click-through rates.',
    recommendationTemplate: 'Add a descriptive <title> tag summarizing the specific page.',
  },
  'seo.meta-description': {
    id: 'seo.meta-description',
    category: 'seo',
    name: 'Meta Description Tag',
    description: 'Verifies existence of <meta name="description"> tag between 50 and 160 characters.',
    defaultSeverity: 'medium',
    weight: 15,
    impactTemplate: 'Search engines may generate unappealing snippet previews in search results.',
    recommendationTemplate: 'Include an engaging 120-160 character meta description tag.',
  },
  'seo.h1': {
    id: 'seo.h1',
    category: 'seo',
    name: 'Single Primary <h1> Heading',
    description: 'Ensures the page has exactly one primary <h1> representing the main page topic.',
    defaultSeverity: 'medium',
    weight: 15,
    impactTemplate: 'Multiple or missing <h1> tags confuse search indexers regarding primary topic.',
    recommendationTemplate: 'Ensure each page has exactly one distinct <h1> element.',
  },
  'seo.open-graph': {
    id: 'seo.open-graph',
    category: 'seo',
    name: 'OpenGraph & Social Sharing Cards (og:title, og:image)',
    description: 'Checks for og:title, og:image, and og:description tags for rich link sharing previews.',
    defaultSeverity: 'low',
    weight: 12,
    impactTemplate: 'Links shared on Twitter, Slack, LinkedIn, and Discord will display without rich image cards.',
    recommendationTemplate: 'Add <meta property="og:title">, <meta property="og:image">, and <meta property="og:description"> tags.',
  },
  'seo.canonical': {
    id: 'seo.canonical',
    category: 'seo',
    name: 'Canonical URL Tag (<link rel="canonical">)',
    description: 'Validates canonical link tag prevents duplicate content indexation.',
    defaultSeverity: 'low',
    weight: 10,
    impactTemplate: 'Without canonical tags, search engines may split ranking signals across parameter variants.',
    recommendationTemplate: 'Add <link rel="canonical" href="https://yourdomain.com/path" /> to <head>.',
  },

  // --- Multimodal Visual & UX Reasoning (Weight 15%) ---
  'visual.cta-prominence': {
    id: 'visual.cta-prominence',
    category: 'visual_ux',
    name: 'Primary CTA Visual Prominence & Contrast',
    description: 'AI visual analysis of conversion hierarchy, button styling, and above-the-fold presence.',
    defaultSeverity: 'high',
    weight: 20,
    impactTemplate: 'Weak CTA visibility directly decreases conversion rates and user onboarding.',
    recommendationTemplate: 'Increase primary button contrast, sizing, and whitespace separation from background elements.',
  },
  'visual.spacing-consistency': {
    id: 'visual.spacing-consistency',
    category: 'visual_ux',
    name: 'Visual Layout Consistency & Spacing Rhythm',
    description: 'AI assessment of grid alignment, padding balance, and typography scale consistency.',
    defaultSeverity: 'medium',
    weight: 15,
    impactTemplate: 'Ragged alignments and erratic margins make products look unfinished or unpolished.',
    recommendationTemplate: 'Standardize Tailwind spacing scales (gap-4, gap-8, py-12, max-w-6xl) across sections.',
  },
  'visual.responsive-composition': {
    id: 'visual.responsive-composition',
    category: 'visual_ux',
    name: 'Multi-Viewport Visual Composition & Balance',
    description: 'Cross-viewport AI inspection of desktop vs. mobile visual balance and content density.',
    defaultSeverity: 'medium',
    weight: 18,
    impactTemplate: 'Awkward line breaks or oversized hero graphics on mobile push value propositions below fold.',
    recommendationTemplate: 'Refine responsive typography breakpoints (text-2xl md:text-5xl) and stack cards on mobile.',
  },
};
